## name: Tokyo Night (day)
## upstream: folke/tokyonight.nvim

foreground               #3760bf
background               #e1e2e7
selection_foreground     #3760bf
selection_background     #c4c8da

cursor                   #3760bf
cursor_text_color        #e1e2e7

url_color                #007197

active_tab_foreground    #3760bf
active_tab_background    #c4c8da
inactive_tab_foreground  #848cb5
inactive_tab_background  #e1e2e7

# black
color0   #e9e9ec
color8   #a1a6c5

# red
color1   #f52a65
color9   #f52a65

# green
color2   #587539
color10  #587539

# yellow
color3   #8c6c3e
color11  #8c6c3e

# blue
color4   #2e7de9
color12  #2e7de9

# magenta
color5   #9854f1
color13  #9854f1

# cyan
color6   #007197
color14  #007197

# white
color7   #6172b0
color15  #3760bf
