"""Generate one Raycast script command per theme.

Raycast matches on the command title, so a command per theme means typing
the theme's name and pressing enter — no dropdown to step through.
"""
import os
import stat
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palettes import THEMES

REPO = os.path.expanduser("~/.dotfiles")
OUT = os.path.join(REPO, "raycast")

TEMPLATE = '''#!/bin/bash

# Raycast Script Command — generated by theme-generator/raycast.py.
# Edit the generator rather than this file.
#
# @raycast.schemaVersion 1
# @raycast.title {display}
# @raycast.mode silent
# @raycast.packageName Theme
#
# @raycast.icon {icon}
# @raycast.description Switch kitty, tmux, nvim, k9s and lazygit to {display}
# @raycast.author Rafael Mian

set -euo pipefail

DOTFILES="${{DOTFILES:-$HOME/.dotfiles}}"

# silent mode swallows stdout, so surface a failure as a Raycast toast
# rather than closing with no sign that anything went wrong.
if ! output="$("$DOTFILES/theme-set" {slug} 2>&1)"; then
  echo "$output"
  exit 1
fi
'''

# A distinct icon per theme, so the commands are recognisable in the list.
ICONS = {
    "kanagawa": "🌊",
    "rose-pine": "🌹",
    "tokyo-night": "🌃",
    "everforest": "🌲",
    "gruvbox-material": "🍂",
}


def generate():
    written = []
    for slug in sorted(THEMES):
        path = os.path.join(OUT, f"theme-{slug}.sh")
        with open(path, "w") as f:
            f.write(TEMPLATE.format(
                display=THEMES[slug]["display"],
                slug=slug,
                icon=ICONS.get(slug, "🎨"),
            ))
        os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in generate():
        print("  wrote", os.path.relpath(p, REPO))
