## name: Everforest (light)
## upstream: neanias/everforest-nvim

foreground               #5c6a72
background               #fdf6e3
selection_foreground     #5c6a72
selection_background     #e0dcc7

cursor                   #5c6a72
cursor_text_color        #fdf6e3

url_color                #3a94c5

active_tab_foreground    #5c6a72
active_tab_background    #e0dcc7
inactive_tab_foreground  #a6b0a0
inactive_tab_background  #fdf6e3

# black
color0   #f4f0d9
color8   #a6b0a0

# red
color1   #f85552
color9   #f85552

# green
color2   #8da101
color10  #8da101

# yellow
color3   #dfa000
color11  #dfa000

# blue
color4   #3a94c5
color12  #3a94c5

# magenta
color5   #df69ba
color13  #df69ba

# cyan
color6   #35a77c
color14  #35a77c

# white
color7   #5c6a72
color15  #5c6a72
