#!/bin/bash

# Raycast Script Command — generated by theme-generator/raycast.py.
# Edit the generator rather than this file.
#
# @raycast.schemaVersion 1
# @raycast.title Rosé Pine
# @raycast.mode silent
# @raycast.packageName Theme
#
# @raycast.icon 🌹
# @raycast.description Switch kitty, tmux, nvim, k9s and lazygit to Rosé Pine
# @raycast.author Rafael Mian

set -euo pipefail

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

# silent mode swallows stdout, so surface a failure as a Raycast toast
# rather than closing with no sign that anything went wrong.
if ! output="$("$DOTFILES/theme-set" rose-pine 2>&1)"; then
  echo "$output"
  exit 1
fi
